name: Deploy website
on:
  push:
   branches:
    -main
jobs:
  deploy:
   runs-on: ubuntu-latest
   steps:
   - name: checkout code
     uses: actions/checkout@v3
   - name: Deploy to server
     uses: appleboy/ssh-action@v0.1.6
     with:
       host: ${{ secrets.HOST}}
       username: ${{ secrets.USERNAME }}
       password: ${{ secrets.PASSWORD }}
       script: |
         cd /var/www/html
         git pull origin main || git clone https://github.com/Sai-sishith09/devops-newprojectt.git .
         sudo systemctl restart nginx
